# Use the official Nginx image as the base
FROM nginx:latest

# Copy your HTML file to the Nginx default web directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to access the web page
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
